### ISSUE TITLE
views incorrectly laid out in threaded-replies branch

### ISSUE THREAD

**Issue by cpmpercussion** [cpmpercussion/microjam#22] opened 2017-07-13 02:10 UTC
views in the threaded-replies branch aren't laid out correctly on small screens.

probably due to changing constraints when instantiating the playback view(s).

<img width="329" alt="screenshot 2017-07-13 12 11 12" src="https://user-images.githubusercontent.com/261139/28147520-83406bd4-67c4-11e7-8eb8-739e193d3717.png">

**Comment by shredlocker** [comment] 2017-07-13 12:29
I think the problem is the size classes again. If you choose the SE model in storyboard, the views are laid out fine in the simulator.

**Comment by shredlocker** [comment] 2017-08-01 11:44
Fixed in #18

**Closed by shredlocker** 2017-08-01 11:44 UTC
Labels: bug
